BOX_IDLE: 0  # empty
BOX_DELIVERING: 1  # empty => occupied
BOX_DELIVERED: 2   # occupied => empty
BOX_RETURNING: 3   # empty => occupied
BOX_RETURNED: 4    # occupied => empty
BOX_ERROR: -1 # both possible

PACKAGE_WAITING_FOR_DELIVERY: '0'
PACKAGE_ENROUTE_DELIVERY: '1'
PACKAGE_DELIVERED_DELIVERY: '2'
PACKAGE_DONE_DELIVERY: '3'
PACKAGE_QUEUING_DELIVERY: '4'
PACKAGE_WAITING_FOR_DROP_OFF: '5'
PACKAGE_ENROUTE_DROP_OFF: '6'
PACKAGE_DROPPED_OFF_DROP_OFF: '7'
PACKAGE_DONE_DROP_OFF: '8'
  
DOOR_OPENED_BY_PIN: '0'
DOOR_OPENED_BY_BARCODE: '1'
DOOR_OPENED_BY_STAFF: '2'

ACTION_NORMAL: 0
ACTION_ABNORMAL: 1
ACTION_ERROR: 2
ACTION_FIX: 3
ACTION_MANUAL: 4
ACTION_MAL: 2

LOG_TYPE_OPEN_BY_PIN: 0
LOG_TYPE_OPEN_BY_BARCODE: 1
LOG_TYPE_OPEN_BY_PRIVILEDGE: 2
LOG_TYPE_INTRUDED: 3
LOG_TYPE_MANUAL: 9

SYNTAX_BOX_ACTION: 0
SYNTAX_BOX_MANUAL_ACTION: 1
SYNTAX_BOX_FIX: 2
SYNTAX_BOX_INTRUDED: 7
SYNTAX_PACKAGE_CREATE: 3
SYNTAX_PACKAGE_ASSIGN: 4
SYNTAX_PACKAGE_ASSIGN_BACKUP: 5
SYNTAX_PACKAGE_DESTROYED: 6

DEVICE_LOG_BARCODE_NOT_EXIST: 0

EMPLOYEE_ROLE_OPERATOR: 1
EMPLOYEE_ROLE_DEVICE_ADMIN: 2

PROXY_SERVER_BASE_URL_1: 'http://60.191.125.50:8080/postInfos.ashx'
