BOX_IDLE: 0  # empty
BOX_DELIVERING: 1  # empty => occupied
BOX_DELIVERED: 2   # occupied => empty
BOX_RETURNING: 3   # empty => occupied
BOX_RETURNED: 4    # occupied => empty
BOX_ERROR: -1 # both possible

PACKAGE_WAITING_FOR_DELIVERY: 0
PACKAGE_ENROUTE_DELIVERY: 1
PACKAGE_DONE_DELIVERY: 2
PACKAGE_QUEUING_DELIVERY: 3
PACKAGE_WAITING_FOR_DROP_OFF: 5
PACKAGE_ENROUTE_DROP_OFF: 6
PACKAGE_DONE_DROP_OFF: 7
  
DOOR_OPENED_BY_PIN: 0
DOOR_OPENED_BY_BARCODE: 1
DOOR_OPENED_BY_STAFF: 2

ACTION_NORMAL: 0
ACTION_WEIRD: 1
ACTION_ERROR: 2
ACTION_FIX: 3