# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
State.create( :name => 'Alabama', :abbr => 'AL', :ansi_code => '1', :statens => '1779775' )
State.create( :name => 'Alaska', :abbr => 'AK', :ansi_code => '2', :statens => '1785533' )
State.create( :name => 'Arizona', :abbr => 'AZ', :ansi_code => '4', :statens => '1779777' )
State.create( :name => 'Arkansas', :abbr => 'AR', :ansi_code => '5', :statens => '68085' )
State.create( :name => 'California', :abbr => 'CA', :ansi_code => '6', :statens => '1779778' )
State.create( :name => 'Colorado', :abbr => 'CO', :ansi_code => '8', :statens => '1779779' )
State.create( :name => 'Connecticut', :abbr => 'CT', :ansi_code => '9', :statens => '1779780' )
State.create( :name => 'Delaware', :abbr => 'DE', :ansi_code => '10', :statens => '1779781' )
State.create( :name => 'Florida', :abbr => 'FL', :ansi_code => '12', :statens => '294478' )
State.create( :name => 'Georgia', :abbr => 'GA', :ansi_code => '13', :statens => '1705317' )
State.create( :name => 'Hawaii', :abbr => 'HI', :ansi_code => '15', :statens => '1779782' )
State.create( :name => 'Idaho', :abbr => 'ID', :ansi_code => '16', :statens => '1779783' )
State.create( :name => 'Illinois', :abbr => 'IL', :ansi_code => '17', :statens => '1779784' )
State.create( :name => 'Indiana', :abbr => 'IN', :ansi_code => '18', :statens => '448508' )
State.create( :name => 'Iowa', :abbr => 'IA', :ansi_code => '19', :statens => '1779785' )
State.create( :name => 'Kansas', :abbr => 'KS', :ansi_code => '20', :statens => '481813' )
State.create( :name => 'Kentucky', :abbr => 'KY', :ansi_code => '21', :statens => '1779786' )
State.create( :name => 'Louisiana', :abbr => 'LA', :ansi_code => '22', :statens => '1629543' )
State.create( :name => 'Maine', :abbr => 'ME', :ansi_code => '23', :statens => '1779787' )
State.create( :name => 'Maryland', :abbr => 'MD', :ansi_code => '24', :statens => '1714934' )
State.create( :name => 'Massachusetts', :abbr => 'MA', :ansi_code => '25', :statens => '606926' )
State.create( :name => 'Michigan', :abbr => 'MI', :ansi_code => '26', :statens => '1779789' )
State.create( :name => 'Minnesota', :abbr => 'MN', :ansi_code => '27', :statens => '662849' )
State.create( :name => 'Mississippi', :abbr => 'MS', :ansi_code => '28', :statens => '1779790' )
State.create( :name => 'Missouri', :abbr => 'MO', :ansi_code => '29', :statens => '1779791' )
State.create( :name => 'Montana', :abbr => 'MT', :ansi_code => '30', :statens => '767982' )
State.create( :name => 'Nebraska', :abbr => 'NE', :ansi_code => '31', :statens => '1779792' )
State.create( :name => 'Nevada', :abbr => 'NV', :ansi_code => '32', :statens => '1779793' )
State.create( :name => 'New Hampshire', :abbr => 'NH', :ansi_code => '33', :statens => '1779794' )
State.create( :name => 'New Jersey', :abbr => 'NJ', :ansi_code => '34', :statens => '1779795')
State.create( :name => 'New Mexico', :abbr => 'NM', :ansi_code => '35', :statens => '897535')
State.create( :name => 'New York', :abbr => 'NY', :ansi_code => '36', :statens => '1779796' )
State.create( :name => 'North Carolina', :abbr => 'NC', :ansi_code => '37', :statens => '1027616')
State.create( :name => 'North Dakota', :abbr => 'ND', :ansi_code => '38', :statens => '1779797')
State.create( :name => 'Ohio', :abbr => 'OH', :ansi_code => '39', :statens => '1085497')
State.create( :name => 'Oklahoma', :abbr => 'OK', :ansi_code => '40', :statens => '1102857')
State.create( :name => 'Oregon', :abbr => 'OR', :ansi_code => '41', :statens => '1155107')
State.create( :name => 'Pennsylvania', :abbr => 'PA', :ansi_code => '42', :statens => '1779798')
State.create( :name => 'Rhode Island', :abbr => 'RI', :ansi_code => '44', :statens => '1219835')
State.create( :name => 'South Carolina', :abbr => 'SC', :ansi_code => '45', :statens => '1779799')
State.create( :name => 'South Dakota', :abbr => 'SD', :ansi_code => '46', :statens => '1785534')
State.create( :name => 'Tennessee', :abbr => 'TN', :ansi_code => '47', :statens => '1325873')
State.create( :name => 'Texas', :abbr => 'TX', :ansi_code => '48', :statens => '1779801')
State.create( :name => 'Utah', :abbr => 'UT', :ansi_code => '49', :statens => '1455989')
State.create( :name => 'Vermont', :abbr => 'VT', :ansi_code => '50', :statens => '1779802')
State.create( :name => 'Virginia', :abbr => 'VA', :ansi_code => '51', :statens => '1779803')
State.create( :name => 'Washington', :abbr => 'WA', :ansi_code => '53', :statens => '1779804')
State.create( :name => 'West Virginia', :abbr => 'WV', :ansi_code => '54', :statens => '1779805')
State.create( :name => 'Wisconsin', :abbr => 'WI', :ansi_code => '55', :statens => '1779806')
State.create( :name => 'Wyoming', :abbr => 'WY', :ansi_code => '56', :statens => '1779807')
